<%!

//   Filename: Styles.inc
//   Generated with CodeCharge 1.2.0
//   JSPTemplates build 05/21/2001



String stylePageBODY = "bgcolor=\"#FFFFFF\" text=\"#000000\" link=\"#0000FF\" vlink=\"#800080\" alink=\"#FF0000\"";
String styleFormTABLE = "cellpadding=\"0\" border=\"0\" cellspacing=\"0\"";
String styleFormHeaderTD = "align=\"center\" bgcolor=\"#0033cc\"";
String styleFormHeaderFONT = "style=\"font-size: 12pt; color: #FFFFFF; font-family: Arial, Tahoma, Verdana, Helvetica; font-weight: bold\"";
String styleFieldCaptionTD = "bgcolor=\"#DEEFFF\"";
String styleFieldCaptionFONT = "style=\"font-size: 10pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica; font-weight: bold\"";
String styleDataTD = "bgcolor=\"#99CCFF\"";
String styleDataFONT = "style=\"font-size: 10pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica\"";
String styleColumnFONT = "style=\"font-size: 10pt; color: #000000; font-family: Arial, Tahoma, Verdana, Helvetica; font-weight: bold\"";
String styleColumnTD = "bgcolor=\"#DEEFFF\"";
%>